package common;

public enum Command {
    CLIENT_CONNECT, CLIENT_DISCONNECT,
    TRAVELER_LOGIN, TRAVELER_LOGOUT, WORKER_LOGIN, WORKER_LOGOUT,
    CREATE_ORDER, GET_ORDER, GET_ALL_ORDERS_BY_TRAVELER, UPDATE_ORDER, CANCEL_ORDER, CONFIRM_ORDER,
    GET_ALL_PARKS, GET_PARK_DETAILS, GET_PARK_AVAILABILITY, UPDATE_PARK_VISITORS,
    PROCESS_ENTRY, PROCESS_EXIT, CHECK_ENTRY_VALID, GET_CURRENT_VISITORS,
    WALKIN_ORDER,
    ADD_TO_WAITLIST, GET_WAITLIST, REMOVE_FROM_WAITLIST,
    REGISTER_SUBSCRIBER, GET_SUBSCRIBER,
    REGISTER_GUIDE, REGISTER_EXISTING_AS_GUIDE,
    GET_PARK_PARAMETERS, REQUEST_PARAMETER_CHANGE, GET_CHANGE_REQUESTS, APPROVE_CHANGE, REJECT_CHANGE,
    CREATE_PROMOTION, APPROVE_PROMOTION, REJECT_PROMOTION,
    GENERATE_VISITS_REPORT, GENERATE_CANCELLATION_REPORT, GENERATE_USAGE_REPORT, GENERATE_TOTAL_VISITORS_REPORT,
    GET_ALL_REPORTS, GET_REPORT,
    GET_NOTIFICATIONS, SEND_REMINDER, CALCULATE_PRICE,
    SUCCESS, FAILURE, ERROR, DATA_RESPONSE
}
